apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- config.yaml
images:
- name: github-actions-argo-cd
  newName: dbatruh/github-actions-argo-cd
  newTag: 2c3bf85c4ef125498e46c910f2efee1c737ef60b
