apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- config.yaml
images:
- name: dbatruh/github-actions-argo-cd
  newName: dbatruh/github-actions-argo-cd
  newTag: c79704019ebdb4f33539b896eca4b36cb054771e
